name: Deploy Frontend

on:
  push:
    branches: [main]

env:
  REGION: us-central1
  PROJECT_ID: lastbit-prj-d-movieapi
  ARTIFACT_REGISTRY: reg-d-movieapi-pipelines

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      - name: Set up GCloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Set up Docker
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev



